// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMetrics.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HealthMetricsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface HealthMetricsRoot : GPBRootObject
@end

#pragma mark - HealthMetric

typedef GPB_ENUM(HealthMetric_FieldNumber) {
  HealthMetric_FieldNumber_MetricName = 1,
  HealthMetric_FieldNumber_Value = 2,
  HealthMetric_FieldNumber_Timestamp = 3,
};

/**
 * Define the message types for health metrics
 **/
GPB_FINAL @interface HealthMetric : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *metricName;

@property(nonatomic, readwrite) float value;

@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - MetricConfiguration

typedef GPB_ENUM(MetricConfiguration_FieldNumber) {
  MetricConfiguration_FieldNumber_MetricNamesArray = 1,
  MetricConfiguration_FieldNumber_SamplingRate = 2,
};

/**
 * Define the message type for specifying metrics and sampling rate
 **/
GPB_FINAL @interface MetricConfiguration : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *metricNamesArray;
/** The number of items in @c metricNamesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metricNamesArray_Count;

@property(nonatomic, readwrite) int32_t samplingRate;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
